---
title: "iTRAQI comparison"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sp)
library(sf)
source("R/download-utils.R")
data_dir <- "U:\\Research\\Projects\\health\\jti_research_data\\jti_itraqi"
```


```{r}
df_facilities <- haven::read_spss(file.path(data_dir, "D_Table_FacilityDescription.sav")) 
df_times <- haven::read_spss(file.path(data_dir, "D_Table_TimeAndLocation_LongFileSELECT.sav"))
df_itraqi_times <- openxlsx::read.xlsx("https://github.com/RWParsons/iTRAQI/blob/main/input/drive_times/Qld_towns_RSQ%20pathways%20V3.xlsx?raw=TRUE", startRow = 3) |> janitor::clean_names()

df_itraqi_times <- openxlsx::read.xlsx("C:/Users/n10891277/R_projects/iTRAQI/input/drive_times/Qld_towns_RSQ pathways V3.xlsx", startRow = 3) |> janitor::clean_names()
```


df_facilities
  centres to add
  - mapoon phc
  - coen phc
  - PORMPURAAW PHC
  - CHILLAGOE PRIMARY HEALTH CENTRE
  - Croydon Primary Health Centre
  - Georgetown Primary Health Centre
  - Palm Island Hospital
  - BOULIA PRIMARY HEALTH CENTRE
  - Birdsville Primary Health Centre


```{r}
# add facilities and their coords for those referred to in the RSQ pathways (iTRAQI) but not in the df_facilities
df_new_facilities_with_coords <- list(
  # FACILITY_NAME_Clean; latitude; longitude
  c("MAPOON PHC", -12.016632475931772, 141.9003317386928),
  c("COEN PHC", -13.944773159917592, 143.20149205490424),
  c("PORMPURAAW PHC", -14.899640079895562, 141.6221141698491),
  c("CHILLAGOE PRIMARY HEALTH CENTRE", -17.14997184798341, 144.52796889646453),
  c("CROYDON PRIMARY HEALTH CENTRE", -18.21097767957882, 142.2401596829941),
  c("GEORGETOWN PRIMARY HEALTH CENTRE", -18.29203373558961, 143.54786222660186),
  c("PALM ISLAND HOSPITAL", -18.730124669326756, 146.57884580498148),
  c("BOULIA PRIMARY HEALTH CENTRE", -22.908133626306732, 139.90838848311506),
  c("TEXAS HOSPITAL", -28.849736273857026, 151.17710790186513),
  c("BIRDSVILLE PRIMARY HEALTH CENTRE", -25.897497103362916, 139.35551489854396)
) %>%
  do.call("rbind", .) |> 
  data.frame() |> 
  setNames(c("FACILITY_NAME_Clean", "Latitude", "Longitude")) |> 
  mutate(across(!FACILITY_NAME_Clean, as.numeric),
         FCLTY_ID = as.numeric(paste0("999", row_number())))

df_facilities <- 
  df_facilities |> 
  filter(!FACILITY_NAME_Clean %in% df_new_facilities_with_coords$FACILITY_NAME_Clean) |> 
  bind_rows(df_new_facilities_with_coords)
```

# visualise iTRAQI paths
```{r}
iTRAQI_vis_app <- function(iTRAQI_paths, facilities) {
  library(shiny)
  library(leaflet)
  library(sf)
  library(sp)
  library(shinyjs)
  
  map_bounds <- list(
    lng1 = 115,
    lat1 = -45.00,
    lng2 = 170,
    lat2 = -5
  )
  
  iTRAQI_paths <-
    iTRAQI_paths |> 
    mutate(
      n_legs = ifelse(destination1 == destination2, 1, 2),
      across(c(destination1, destination2), str_to_title),
      destinations_popup = ifelse(n_legs == 1, 
                                  glue::glue("Destination: {destination1} ({transport_mode1})"),
                                  glue::glue("Destination 1: {destination1} ({transport_mode1})<br>",
                                             "Destination 2: {destination2} ({transport_mode2})")),
      popup = glue::glue(
      "<b>{town_name}</b><br>",
      "Travel legs: {n_legs}<br>",
      "{destinations_popup}<br>",
      "Travel time: {total_transport_time_min} mins"
    ))
  
  facilities <-
    facilities |> 
    filter(!is.na(Latitude), !is.na(Longitude)) |> 
    rename(xcoord = Longitude, ycoord = Latitude)
  
  # df_paths <- map_dfr(iTRAQI_paths$town_point, function(tp) {
  #   df_destinations <-
  #     iTRAQI_paths |> 
  #     filter(town_point == tp) |> 
  #     select(town_point, destination1, destination2) |>
  #     pivot_longer(!town_point, names_to = "destination_order", values_to = "destination") |> 
  #     mutate(destination = toupper(destination)) |> 
  #     left_join(
  #       select(facilities, FACILITY_NAME_Clean, FCLTY_ID, xcoord, ycoord), 
  #       by = c("destination" = "FACILITY_NAME_Clean")
  #     )
  #   
  #   df_destinations_plus_origin <- bind_rows(
  #     select(filter(iTRAQI_paths, town_point == tp), xcoord, ycoord),
  #     df_destinations
  #   ) |> 
  #     mutate(id = paste0("P", tp))
  #   
  #   df_destinations_plus_origin
  # })
  
  
  
  ui <- 
    navbarPage(
      "iTRAQI",
      id = "nav",
      tabPanel(
        "Map",
        useShinyjs(),
        div(
          class = "outer",
          tags$head(
            includeCSS("styles.css"),
            tags$script(src = "script.js")
          ),
          leafletOutput("map", width = "100%", height = "100%"),
        )
      )
    )
  
  server <- function(input, output, session) {
    output$map <- renderLeaflet({
      map <- 
        leaflet(options = leafletOptions(minZoom = 5)) |> 
        setMaxBounds(
          lng1 = map_bounds$lng1, lat1 = map_bounds$lat1,
          lng2 = map_bounds$lng2, lat2 = map_bounds$lat2
        ) |> 
        addMapPane(name = "layers", zIndex = 200) |> 
        addMapPane(name = "maplabels", zIndex = 400) |> 
        addMapPane(name = "markers", zIndex = 206) |> 
        addProviderTiles("CartoDB.VoyagerNoLabels") |> 
        addProviderTiles("CartoDB.VoyagerOnlyLabels",
          options = leafletOptions(pane = "maplabels"),
          group = "map labels"
        ) |> 
        hideGroup(paste0("F", facilities$FCLTY_ID)) |> 
        addCircleMarkers(
          layerId = iTRAQI_paths$town_point,
          lng = iTRAQI_paths$xcoord, 
          lat = iTRAQI_paths$ycoord,
          radius = 2, 
          fillOpacity = 0,
          popup = iTRAQI_paths$popup
        ) |> 
        addCircleMarkers(
          layerId = paste0("F", facilities$FCLTY_ID),
          group = paste0("F", facilities$FCLTY_ID),
          lng = facilities$xcoord,
          lat = facilities$ycoord,
          radius = 3, 
          fillOpacity = 0.2,
          color = "red"
        )
    })
    
    observeEvent(input$map_marker_click, {
      print(input$map_marker_click)
      df_destinations <-
        iTRAQI_paths |> 
        filter(town_point == input$map_marker_click$id) |> 
        select(town_point, destination1, destination2) |>
        pivot_longer(!town_point, names_to = "destination_order", values_to = "destination") |> 
        mutate(destination = toupper(destination)) |> 
        left_join(
          select(facilities, FACILITY_NAME_Clean, FCLTY_ID, xcoord, ycoord), 
          by = c("destination" = "FACILITY_NAME_Clean")
        )
      
      df_destinations_plus_origin <- bind_rows(
        select(filter(iTRAQI_paths, town_point == input$map_marker_click$id), xcoord, ycoord),
        df_destinations
      )
      
      # df_paths_i <- df_paths |> filter(id == paste0("P", input$map_marker_click$id))
      
      leafletProxy("map") |> 
        hideGroup(paste0("F", facilities$FCLTY_ID)) |> 
        showGroup(paste0("F", df_destinations$FCLTY_ID)) |> 
        addPolylines(
          lng = df_destinations_plus_origin$xcoord,
          lat = df_destinations_plus_origin$ycoord
        )
    })
    
  }
  shinyApp(ui = ui, server = server)
}

iTRAQI_vis_app(iTRAQI_paths = df_itraqi_times, facilities = df_facilities)
```


```{r}
iTRAQI_paths |> 
  filter(town_point == input$map_marker_click$id) |>
  select(town_point, destination1) 
```


```{r}
df_itraqi_times |> plyr::count("destination1") |> arrange(desc(freq))

df_itraqi_dests <-
  df_itraqi_times |> 
  select(town_point, destination1, destination2) |> 
  pivot_longer(!town_point) |> 
  mutate(value = str_trim(toupper(value)))

# check that there are coordinates for all included facilities in iTRAQI paths
df_itraqi_dests |> 
  mutate(value = str_trim(toupper(value))) |> 
  select(value) |> 
  distinct() |> 
  rownames_to_column("n") |> 
  filter(!is.na(value)) |> 
  left_join(df_facilities, by = c("value" = "FACILITY_NAME_Clean")) |> 
  filter(is.na(Latitude))

df_itraqi_dests |> 
  select(value) |> 
  distinct() |> 
  mutate(value = toupper(value)) |> 
  rownames_to_column("n") |> 
  filter(!is.na(value)) |> 
  # filter(value %in% c("INGHAM", "BUNDABERG")) |> 
  left_join(df_facilities, by = c("value" = "FACILITY_NAME_Clean")) 

```


```{r}

```

